apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd-demo

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: cicd-demo
    newName: ghcr.io/snakepy512/learn-ai
    newTag: 273a28b74f69c3d45a9298eeda42ba0e08c5b74e