apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd-demo

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: cicd-demo
    newName: cicd-demo
    newTag: local