apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd-demo

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: cicd-demo
    newName: ghcr.io/snakepy512/learn-ai
    newTag: 59b18ae5113a0928506961c2cfe4f6aed6a27cdb